name: Project CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0 # Specify the Go version you want to use
      - uses: actions/checkout@v3
      - name: Unit test
        run: make test
